src/BaGet.Core/Extensions/PackageArchiveReaderExtensions.cs

Allow README to be in a folder other than the root

use StripLeadingDirectorySeparators by GetReadmeAsync

---

.gitignore
CONTRIBUTING.md
Dockerfile
LICENSE
docs/advanced/debugging.md
docs/configuration.md
docs/installation/docker.md
readme.md
samples/BaGetterWebApplication/appsettings.json
src/BaGetter/appsettings.json
src/readme.md

Changed the docker container, so it is using the `/data` folder for persisting the packages files, symbols and sqlite db file and not the `/app` folder. The `/data` folder can be pulled-out with a single `-v data:/data` to the docker host.
Changed doc: The default port on the Docker host is 8080 and not 80.
Updated the readme.md

Using data folder in Docker

---

tests/BaGetter.Core.Tests/Metadata/RegistrationBuilderTests.cs

There is a problem in a unit test where no default pblish date is set for packages so the year 0001 is used which leads to a overflow of DateTimeOffset.
bagetter/BaGetter#32

✅ Using UtcNow to prevent offset overflow

---

docs/installation/docker.md

The ports used in the documetation for Docker are inconsistent and will not work as documented.
The port used in `docker run` is different from all following commands.
This PR fixes that and uses `5000` to be consistent with all other docs.

Use consistent port in documentation for Docker

---

src/BaGetter.Database.Sqlite/BaGetter.Database.Sqlite.csproj
src/BaGetter.Database.Sqlite/SqliteContext.cs
src/Directory.Build.props

As mentioned in bagetter/BaGetter#38 under some special configurations Sqlite failed with a "folder not found" exception.
This PR solves this issue. It checks the config and creates the folder under Windows or *nix like OS during the database migration respecting full qualified path or relative paths.
Addresses https://github.com/bagetter/BaGet/issues/38

Create the folders for the Sqlite blob files if they do not exist.

---

Directory.Packages.props
src/BaGetter.Database.SqlServer/BaGetter.Database.SqlServer.csproj

This PR fixes #42 and also updates some dependencies of `EntityFrameworkCore`.
The direct dependency to `Microsoft.Data.SqlClient` is referenced with a [version range](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges) which garantuees a version with the bug fixed is restored.

Fix issue #42 (High vulnerability in docker image)

---

src/BaGetter/Program.cs

(The below is also being prepared for inclusion in the documentation for `bagetter.github.io`.)
Mostly useful when running containerised (e.g. using Docker, Podman, Kubernetes, etc), the application will look for
files named in the same pattern as environment variables under `/run/secrets`, or under the `secrets` subfolder of the
path set by `BAGET_CONFIG_ROOT` - for example, if `BAGET_CONFIG_ROOT=/etc/baget`:
```
/etc/baget/secrets/Database__ConnectionString
/run/secrets/Database__ConnectionString
```
If `BAGET_CONFIG_ROOT` is unset, only the `/run/secrets` path will be used. Currently, the load order is such that
values in `/run/secrets` will supersede those in `/etc/baget/secrets`.
This allows for sensitive values to be provided individually to the application, typically by …

Allow the use of secret files for configuration

---

docs/docusaurus.config.ts

Fix links to Github and "Edit this page"
Taking a look at [original Docusaurus configuration](https://github.com/facebook/docusaurus/blob/c1ac06768bd3cb997c11931209a97e8c9574c11d/website/docusaurus.config.ts#L398) it seems that usage of "organizationName" and "projectName" configuration variables is very limited.
For example, they cannot be used in "presets" -> "docs" -> "editUrl".
"editUrl" can be a function (see [link1](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#configuration) [link2](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#EditUrlFunction)) but it still doesn't receive the "Config" object.
So, "variables" were replaced with hard-coded values, unfortunatelly

Fix docusaurus.config.ts

---

Directory.Packages.props
src/Directory.Build.props
tests/BaGetter.Core.Tests/BaGetter.Core.Tests.csproj
tests/BaGetter.Protocol.Tests/BaGetter.Protocol.Tests.csproj
tests/BaGetter.Tests/BaGetter.Tests.csproj
tests/BaGetter.Web.Tests/BaGetter.Web.Tests.csproj
tests/Directory.Build.props

This PR removes the explicit reference to `Microsoft.SourceLink.GitHub` because it is included in the SDK.
Also the `pdb` files are removed from the `nupkg` to save some space.
According to the documentation this is only needed for older versions of VisualStudio (which don't support .NET 8).
I also removed some duplicate entries in the test projects.
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects
>...
> If your project uses .NET SDK 8+ and is hosted by the above providers it does not need to reference any Source Link packages or set any build properties.
> Referencing any Source Link package in a .NET SDK 8+ project suppresses Source Link that is included in the SDK.
> ...
https://github.com/dotnet/sourcelink#pdb-distributions
> ...
> If you distribute the library …

Remove explicit referenced SourceLink

---

src/BaGetter.Core/Extensions/DependencyInjectionExtensions.cs

This small PR fixes a `TODO` comment by refactoring to a switch expression.

Fix Todo comment (use switch expression)

---

.github/workflows/release.yml

This PR fixes a mistake reading the `PackageSource` variable which is required for publishing to api.nuget.org.

Fix: NuGet release problem

---

src/BaGetter.Core/Metadata/BaGetRegistrationIndexPageItem.cs
src/BaGetter.Core/Metadata/BaGetterPackageMetadata.cs
src/BaGetter.Core/Metadata/BaGetterRegistrationIndexPage.cs
src/BaGetter.Core/Metadata/BaGetterRegistrationIndexResponse.cs
tests/BaGetter.Core.Tests/Metadata/ModelTests.cs
tests/BaGetter.Tests/ApiIntegrationTests.cs
tests/BaGetter.Tests/BaGetter.Tests.csproj

This PR fixes a TODO comment.
As mentioned all classes (in registration) do derive now from the base classes.
The tests were adjusted accordingly.
The `[JsonPropertyOrder(int.MaxValue)]` is necessary, because otherwise the properties of the base class are serialized last and too many tests had to be adjusted.

Fix Todo comment (derived classes in registration)

---

docs/docs/Advanced/sdk.md
docs/docs/Import/local-feeds.md
docs/docs/Import/nugetorg.md
docs/docs/Import/nugetserver.md
docs/docs/Index.md
docs/docs/Installation/aws.md
docs/docs/Installation/azure.md
docs/docs/Installation/docker.md
docs/docs/Installation/gcp.md
docs/docs/Installation/iis-proxy.md
docs/docs/Installation/local.md
docs/docs/configuration.md
docs/docs/vs/liget.md
docs/docs/vs/local-feeds.md
docs/docs/vs/nugetorg.md
docs/docs/vs/nugetserver.md
docs/docusaurus.config.ts

This PR fixes some issues with syntax highlighting in the documentation.
This is done by adding support for missing languages.
I also added some comments to the `docs/docusaurus.config.ts` file for reference.
Example images:

Fix Syntax Highlighting in documentation

---

Directory.Packages.props

This PR updates the dependency for `MySQL` from `beta-2` to `GA`.

Update `Pomelo.EntityFrameworkCore.MySql` from beta to GA

---

src/BaGetter.Web/Pages/Index.cshtml

This PR adss a comma between the authors on the index page. This is similar to the `Authors` section on the package page.

Fix display of authors on index page

---

src/BaGetter.Web/wwwroot/css/site.css

This PR fixes the display of tags on the index page by increasing the line height to prevent letters being cut off.

Fix display of tags on index page

---

src/BaGetter.Web/wwwroot/css/site.css

This PR adjusts the color of the copy and search buttons to be the same (like on the official gallery) and fixes the hover color of the search button (like on the official gallery).

Adjust color of copy and search buttons

---

src/BaGetter.Web/Pages/Package.cshtml
src/BaGetter.Web/wwwroot/css/site.css

This PR adds a section `Tags` to the package page similar to the official gallery and the already existing `Authors` section.

Display tags on package page

---

Directory.Packages.props
src/BaGetter.Web/Pages/Package.cshtml
src/BaGetter.Web/Pages/Package.cshtml.cs

This PR adds the feature to parse the realease notes as Markdown to enable all the features like with the Readme.
Also the dependency `Markdig` was updated to the latest version.
The link is just text.
The link is an actual link.

Parse release notes as Markdown

---

src/BaGetter/Startup.cs

Thanks to https://github.com/dotnet/runtime/issues/38491 being merged, we can clean this one up now. This feels like integrating a change by @loic-sharma himself :-)

Remove workaround and configure BaGetter options directly

---

docs/docs/configuration.md
src/BaGetter.Core/Configuration/BaGetterOptions.cs
src/BaGetter.Core/Configuration/PackageOverwriteAllowed.cs
src/BaGetter.Core/Entities/Package.cs
src/BaGetter.Core/Indexing/PackageIndexingService.cs
tests/BaGetter.Core.Tests/Services/PackageIndexingServiceTests.cs

This adds a mode `PrereleaseOnly` to the `AllowPackageOverwrites` configuration setting. 
It's now an enum, but I kept the others as "True" and "False" so booleans can still be used in the appsettings files, keeping them backwards compatible.
Closes #69

Prerelease package overwrites

---

docs/docs/configuration.md
src/BaGetter.Core/Configuration/BaGetterOptions.cs
src/BaGetter.Core/Configuration/HealthCheckOptions.cs
src/BaGetter.Core/Validation/ValidateStartupOptions.cs
src/BaGetter/Startup.cs
src/BaGetter/appsettings.json

* Added the most basic healthz endpoint
Addresses https://github.com/bagetter/BaGet/issues/105
I tried adding the database provider health checks at the same time, however the way the registration of those via the IProvider interface made it a lot more difficult than I have time for right now.

add basic healthcheck feature #105

---

docs/docs/Index.md
docs/docs/configuration.md
src/BaGetter.Core/Configuration/BaGetterOptions.cs
src/BaGetter/ConfigureBaGetterOptions.cs
src/BaGetter/ConfigureBaGetterServer.cs
src/BaGetter/Startup.cs
src/BaGetter/ValidateBaGetterOptions.cs
src/BaGetter/appsettings.json

Is there a limit we should stay in? The whole thing might be in memory while uploaded, for example in the AWS storage service, temporarily hiking RAM usage to up to ~8GB (or whatever limit we set). Should we put an info box somewhere that tells people that uploaded packages will be temporarily in memory, thus possibly spiking RAM?
Closes #101

Increase max package size to ~8GB

---

.github/workflows/release.yml

This PR adds the correct version to the binaries when releasing a new version.
Instead of `1.0.0.0` all binaries have the same version as the used tag.
This fixes issue #109.

Add correct version to binaries

---

.github/workflows/release.yml
BaGetter.sln
docs/docs/Index.md
docs/docs/configuration.md
src/BaGetter.Core/Configuration/BaGetterOptions.cs
src/BaGetter.Web/BaGetter.Web.csproj
src/BaGetter.Web/Extensions/HtmlHelperExtensions.cs
src/BaGetter.Web/Helper/ApplicationVersion.cs
src/BaGetter.Web/Helper/ApplicationVersionHelper.cs
src/BaGetter.Web/Pages/Shared/_Layout.cshtml
src/BaGetter.Web/wwwroot/css/site.css
src/BaGetter/ConfigureBaGetterServer.cs
src/BaGetter/Startup.cs
src/BaGetter/ValidateBaGetterOptions.cs
src/BaGetter/appsettings.json
src/Directory.Build.props
src/Directory.Build.targets

This PR adds a footer to the Website displaying the current running version of BaGetter.
This fixes a part of the requests from #102.
Current state:
**Todo**
Currently there is no version assigned to the binaries of BaGetter. So `1.0.0.0` is always shown.

Display version of BaGetter in a footer on Website

---

src/BaGetter.Protocol/Models/SearchResult.cs
tests/BaGetter.Protocol.Tests/Models/PackageMetadataTests.cs
tests/BaGetter.Protocol.Tests/Models/SearchResultTests.cs

As pointed out by @Splamy (via discord) the [official documentation](https://docs.microsoft.com/nuget/api/search-query-service-resource#search-result) states that `Tags` (and `Authors`) can be 
> string or array of strings
This PR fixes that for `Tags` (including tests) and also adds the tests for `Authors`.
Also I noticed false positives in the tests for `PackageMetadata` (my fault) which I fixed.

Fix serialization of `SearchResult`

---

.github/workflows/release.yml
Dockerfile

Passes the assembly version to the `dotnet publish` step inside the Dockerfile.
Example manual build of this PR:
- `docker build -t local-bagetter:1.1.1-test --build-arg Version=1.1.1-test .`
- `docker run --rm -p 8080:8080 local-bagetter:1.1.1-test`
Addresses #122

Include version in Docker image

---

Directory.Packages.props
docs/docs/configuration.md
src/BaGetter.Core/BaGetter.Core.csproj
src/BaGetter.Core/Configuration/HealthCheckOptions.cs
src/BaGetter.Core/Extensions/DependencyInjectionExtensions.Providers.cs
src/BaGetter.Core/Extensions/HealthCheckExtensions.cs
src/BaGetter/Startup.cs
tests/BaGetter.Tests/Support/BaGetApplication.cs

This will return a json like this from the /health endpoint:
```json
{
"Status": "Healthy",
"Sqlite": "Healthy"
}
```
If `ListConfiguredServices` is turned off, anything but the general `Status` is omitted.  
Alternatively, we could not omit the specific checks entirely but just change the specific service name (e.g. `Sqlite`) to what the service is used for (e.g. `Database`). 
The db health checks are identified using a tag that simply holds the service. That way any registered health check can be compared to the configuration so only active services are checked.  
Alternatively (1), I could add the `BaGetter` tag to the health checks and use that as additional filter. That way, someone adding BaGetter to their own application could also have their own health checks named/tagged whatever …

Add database health check

---

src/BaGetter.Web/Extensions/IServiceCollectionExtensions.cs
src/BaGetter.Web/Helper/ApplicationVersionHelper.cs
src/BaGetter.Web/Pages/Shared/_Layout.cshtml
src/BaGetter.Web/Pages/Statistics.cshtml

Currently the statistics page only shows the numbers part of the version, e.g. 1.1.1, instead of the full version shown in the footer. This PR injects the `ApplicationVersion` object from the footer in order to use the same data source and shows the full version including commit hash.
There's also less reflection this way.

feat(Statistics): Show full version

---

Directory.Packages.props
docs/docs/Index.md
docs/docs/Installation/azure.md
docs/docusaurus.config.ts
src/BaGetter.Azure/AzureApplicationExtensions.cs
src/BaGetter.Azure/BaGetter.Azure.csproj
src/BaGetter.Azure/Configuration/AzureBlobStorageOptions.cs
src/BaGetter.Azure/Extensions/StorageExceptionExtensions.cs
src/BaGetter.Azure/Storage/BlobStorageService.cs
src/BaGetter/Startup.cs

This adds the new API of Azure Blob Storage as storage provider. Other azure providers remain deactivated as they have to be migrated to the new APIs too. 
Tested with both AccessKey and ConnectionString configurations.
Addresses #127.

feat(Storage): Add Azure Blob Storage provider

---

Directory.Packages.props
docs/docs/Installation/azure.md
src/BaGetter.Azure/AzureApplicationExtensions.cs
src/BaGetter.Azure/BaGetter.Azure.csproj
src/BaGetter.Azure/Configuration/AzureTableOptions.cs
src/BaGetter.Azure/Extensions/StorageExceptionExtensions.cs
src/BaGetter.Azure/Table/PackageEntity.cs
src/BaGetter.Azure/Table/PackageEntityExtensions.cs
src/BaGetter.Azure/Table/TableOperationBuilder.cs
src/BaGetter.Azure/Table/TablePackageDatabase.cs
src/BaGetter.Azure/Table/TableSearchService.cs
src/BaGetter.Core/Content/IPackageContentService.cs
src/BaGetter.Web/Controllers/PackageContentController.cs
src/BaGetter/Startup.cs

This one was complicated, I hope I didn't forget anything. DB type is `AzureTable`, and it also adds a search provider for the `Database` search type, as azure tables are not normal database and can therefore not use ef core like the rest.
This does not add Azure AI Search support.
This is a part of #28 .

feat(Database): Add Azure Table Storage API

---

src/BaGetter.Aws/AwsApplicationExtensions.cs
src/BaGetter.Aws/S3StorageOptions.cs

To be able to use S3 buckets not in AWS, for example Linode, allow the option to set the Service URL in settings.
Example appsettings to configure:
```json
"Storage": {
"Type": "AwsS3",
"Endpoint": "https://eu-central-1.linodeobjects.com",
"Bucket": "testbucket",
"AccessKey": "***",
"SecretKey": "***"
},
```
or 
```json
"Storage": {
"Type": "AwsS3",
"Region": "eu-central-1",
"Bucket": "testbucket",
"AccessKey": "***",
"SecretKey": "***"
},
```
RegionEndpoint and ServiceUrl are mutually exclusive

Add and Endpoint option to be able to set ServiceURL

---

docs/docs/Installation/docker.md

docs: Fix a typo in the docker installation guide

---

src/BaGetter.Azure/Table/TableSearchService.cs

* Fixed incorrect table name when using a custom table name.
Addresses #157

Fixed using incorrect table name.

---

src/BaGetter.Azure/Table/TablePackageDatabase.cs

* Set id to lower invariant when querying Azure Table.
Addresses #159

Set id to lower invariant when querying Azure Table.

---

src/BaGetter.Core/Extensions/PackageArchiveReaderExtensions.cs

Allow package repository urls to be http as discussed in https://github.com/bagetter/BaGetter/issues/151.

fix: Allow package repository urls to be http.

---

docs/docs/configuration.md
global.json
src/BaGetter.Core/Configuration/BaGetterOptions.cs
src/BaGetter.Core/Indexing/IPackageDeletionService.cs
src/BaGetter.Core/Indexing/PackageDeletionService.cs
src/BaGetter.Core/Indexing/PackageIndexingService.cs
tests/BaGetter.Core.Tests/Services/PackageIndexingServiceInMemoryTests.cs
tests/BaGetter.Core.Tests/Services/PackageIndexingServiceTests.cs
tests/BaGetter.Core.Tests/Support/InMemoryPackageDatabase.cs

Added a new optional setting `MaxVersionsPerPackage` to auto delete packages when there are more than `MaxVersionsPerPackage` versions. We have been running out of space regularly on our bagetter server and been looking for a system to auto clean.
I added corresponding unit tests, this required adding a `InMemoryPackageDatabase` implementation. All unit tests do pass.

New MaxVersionsPerPackage to clean packages

---

Directory.Packages.props
tests/BaGetter.Core.Tests/BaGetter.Core.Tests.csproj
tests/BaGetter.Protocol.Tests/BaGetter.Protocol.Tests.csproj
tests/BaGetter.Tests/BaGetter.Tests.csproj
tests/BaGetter.Web.Tests/BaGetter.Web.Tests.csproj

Updated all packages to latest versions. Removes some vulnerabilities, especially in the Postgres libraries.

Update packages to latest versions

---

.github/workflows/release.yml

Adds upon PR https://github.com/bagetter/BaGetter/pull/117 which addressed issue https://github.com/bagetter/BaGetter/issues/116.
This would provide a helm chart repo facility for folks using GitOps utilities.

Add helm chart release action

---

docs/docs/configuration.md
src/BaGetter.Core/Configuration/RetentionOptions.cs
src/BaGetter.Core/Indexing/PackageIndexingService.cs
tests/BaGetter.Core.Tests/Services/PackageIndexingServiceInMemoryTests.cs

IMO we should also change it so the prerelease limiter limits the total number of prereleases per patch, not builds per prerelease label. So when I exceed the limit by pushing a `-beta.*` package, the oldest `-alpha` package should be deleted. What do you think?

chore: Fix naming and docs for retention configuration parameters

---

docs/docs/Installation/docker.md

docs: Improve docker hosting information

---

src/BaGetter/ConfigureBaGetterServer.cs

This updates the `Configure` method in `src/Bagetter/ConfigureBaGetterServier.cs` to include the missing `XForwardedHost` flag in the `ForwardedHeaders` options. This change ensures that when running behind a reverse proxy, the proper host header is used for generating URLs correctly.
**Addresses:** [#205](https://github.com/bagetter/BaGet/issues/205)

Fix: Add XForwardedHost to ForwardedHeaders (#205)

---

docs/docs/Installation/docker.md

Added an example for an Apache 2 reverse proxy configuration
* Added an example of an Apache 2 configuration for the reverse proxy. Added a point regarding binding the internal service to 127.0.0.1 only for security reasons

Update docker.md - Apache 2 reverse proxy example
