.github/PULL_REQUEST_TEMPLATE.md, Dockerfile, readme.md
* Various updates to move to bagetter org
=> Updates to bagetter

src/Directory.Build.props
I updated the informations shown on NuGet.org for BaGetter.
Addresses https://github.com/bagetter/BaGet/issues/25
=> :sparkles: Updated the Directory.Build.props for NuGet infos.

readme.md
This PR updates the ReadMe:
- add badge to latest version of docker image
- add/fix missing links
- fix formatting according to MarkdownLint
=> Update ReadMe (add docker badge, fix missing links)

docs/docs/configuration.md
This PR adds the documentation for the feature `secret files in docker` introduced by PR #41
=> add doc about secret files in docker

Directory.Packages.props
This PR updates the dependencies for the tests to the latest version.
=> Update dependencies for tests

Directory.Packages.props
This PR updates the official `NuGet.*` packages to the latest version.
=> Update the official `NuGet.*` packages

.github/workflows/main.yml
This PR adjusts the `main.yml` to run everything on multiple operating systems to account for changes in line endings.
=> Rrun CI on multiple operating systems

src/BaGetter.Core/Extensions/PackageArchiveReaderExtensions.cs, src/BaGetter.Core/Upstream/Clients/V3UpstreamClient.cs, src/BaGetter.Protocol/Models/PackageMetadata.cs, tests/BaGetter.Core.Tests/Upstream/V3UpstreamClientTests.cs, tests/BaGetter.Protocol.Tests/Models/PackageMetadataTests.cs, tests/BaGetter.Protocol.Tests/RawPackageMetadataClientTests.cs, tests/BaGetter.Protocol.Tests/Support/TestDataHttpMessageHandler.cs, tests/BaGetter.Protocol.Tests/TestData.Designer.cs, tests/BaGetter.Protocol.Tests/TestData.resx
This PR fixes #89.
Also some tests were added to verify the fix.
=> Fix issue #89

docs/docs/configuration.md
Incorporates requested changes by @loic-sharma in #98, I merged a bit too hastily there.
=> Use language-agnostic microsoft links, and improve docs

docs/docs/configuration.md, src/BaGetter/appsettings.json
This improves discoverability.
=> feat: Change default to services being listed on the statistics page

src/BaGetter.Core/Extensions/DependencyInjectionExtensions.cs, src/BaGetter.Web/Pages/Shared/_Layout.cshtml, src/BaGetter.Web/Pages/Statistics.cshtml, src/BaGetter.Web/Pages/Statistics.cshtml.cs, src/BaGetter/Startup.cs
Also moves the StatisticsService registration from providers to default application services.
=> fix(Statistics): Directly inject StatisticsOptions

.github/workflows/release.yml
*Add arm and amd both architecture image support in release pipeline
[Addresses https://github.com/bagetter/BaGet/issues/123](https://github.com/bagetter/BaGetter/issues/134)
=> add arm docker image support

docs/docs/Installation/aws.md
=> Add docs for S3-compatible storage

.github/workflows/release.yml
Reverts bagetter/BaGetter#135 to restore release pipeline
=> Revert "add arm docker image support"

.github/workflows/release.yml, Dockerfile, readme.md
I've looked into building ARM based Docker Images and this is the solution that worked on my private repo.
I tried the Docker image on my Raspberry Pi and it worked fine there.
This solves issue https://github.com/bagetter/BaGetter/issues/134
=> Docker ARM support

docs/docs/configuration.md
Addresses https://github.com/bagetter/BaGet/issues/143
=> docs: Add custom host path to documentation

readme.md
As someone asked how to do it, it's not obvious enough so here's more documentation. Gotta work on the documentation on the website too, on a later date.
=> docs: Add IIS to the getting started readme section

.github/workflows/release.yml
I would like to have tags for major and minor release for more granular updates.
=> Create additional docker image tags for major and minor version

docs/docs/configuration.md
* update the example format
* additional explanations
=> Update Docker Compose example

BaGetter.sln, Directory.Packages.props, docs/docs/Installation/tencent.md, readme.md, src/BaGetter.Core/Statistics/StatisticsService.cs, src/BaGetter.Tencent/BaGetter.Tencent.csproj, src/BaGetter.Tencent/BucketClient.cs, src/BaGetter.Tencent/TencentApplicationExtensions.cs, src/BaGetter.Tencent/TencentCosClient.cs, src/BaGetter.Tencent/TencentStorageOptions.cs, src/BaGetter.Tencent/TencentStorageService.cs, src/BaGetter/BaGetter.csproj, src/BaGetter/Startup.cs, src/BaGetter/ValidateBaGetterOptions.cs, src/BaGetter/appsettings.json, src/readme.md
1、IStorageService support tencent cloud ocs
2、add docs
=> add tencent cloud ocs support

.github/workflows/release.yml
=> ci: Add quotes around directory string

docs/docs/Installation/iis-proxy.md
=> docs: Add runtime version to IIS installation

src/BaGetter.Web/wwwroot/css/site.css
This adds a dark mode that will be active according to the OS or browser's settings. 
Would like some feedback as I'm usually not great with colour choices. Here's some screenshots:
=> Add dark mode theme
